### ISSUE TITLE
01 last bits

### ISSUE THREAD

**Issue by boulderrinnlab** [boulderrinnlab/CLASS_2020#78]
I fixed most of the other counts in previous one and now just left with:

~60: quartile of 250 peaks filter.
~120: ks.test doesn't run
~255 The figure of peaks vs overlap for all promoters has intercept of 1,200 peaks?

****** 354 I did a length and summary and summary seems that min is 46 overlaps so no dbps don't bind any promters, but length is 161 ? ******* please double check

~364 need help with ggplot -- seems like there is a simply way to plot this with indexing lncRNA and mRNa overlaps in aes()

**Comment by msmallegan** [comment]
Re: ~120 ks.test -- the test does run for me, however, it does give a warning regarding ties in the ranking. This is okay, and I believe the ks.test results are still valid.

**Comment by msmallegan** [comment]
Re: ~354 length summary -- that's correct that the length of the num_ovl should be the total number of DBPs and that there are none that don't bind any promoters.
